TELEGRAM_TOKEN="8481211490:AAHtgpfxxsvb6vkz3Y5tQNSVaMcgb0pIp4Q"
SUPABASE_URL = "https://kxergoynyjvbnsrgkobn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZXJnb3lueWp2Ym5zcmdrb2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3MDUyMzgsImV4cCI6MjA4MTI4MTIzOH0.gAfSqXLwEiiEXy7vdVm33qTll9hTjScvd_NyDYKxhbo"
FMP_KEY="wUIhqooGab6bHP6KSsPBlE5dHAwvSgWI"